<?php

use Illuminate\Database\Seeder;
use Mobilocator\Kelurahan;

class KelurahansTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = new Kelurahan;
			$data->nama = 'Cibodas';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cibogo';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cikahuripan';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cikidang';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cikole';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Gudangkahuripan';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Jayagiri';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Kayuambon';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Langensari';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Lembang';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mekarwangi';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Pagerwangi';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sukajaya';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Suntenjaya';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Wangunharja';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Wangunsari';
			$data->id_kec = '1';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cipada';
			$data->id_kec = '2';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Jambudipa';
			$data->id_kec = '2';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Kertawangi';
			$data->id_kec = '2';
			$data->save();
        $data = new Kelurahan;
			$data->nama = 'Padaasih';
			$data->id_kec = '2';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Pasirhalang';
			$data->id_kec = '2';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Pasirlangu';
			$data->id_kec = '2';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sadangmekar';
			$data->id_kec = '2';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Tugumukti';
			$data->id_kec = '2';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Bojongkoneng';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cilame';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cimanggu';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cimareme';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Gadobangkong';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Margajaya';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mekarsari';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ngamprah';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Pakuhaji';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sukatani';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Tanimulya';
			$data->id_kec = '3';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cempakamekar';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ciburuy';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cimerang';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cipeundeuy';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Jayamekar';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Kertajaya';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Kertamulya';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Laksanamekar';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Padalarang';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Tagogapu';
			$data->id_kec = '4';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cipatat';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ciptaharja';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cirawamekar';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Citatah';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Gunungmasigit';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Kertamukti';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mandalasari';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mandalawangi';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Nyalindung';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Rajamandala Kulon';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sarimukti';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sumurbandung';
			$data->id_kec = '5';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cikalong';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cipada';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ciptagumati';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cisomang Barat';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ganjarsari';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Kanangasari';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mandalamukti';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mandalasari';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mekarjaya';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Puteran';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Rende';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Tenjolaut';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Wangunjaya';
			$data->id_kec = '6';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Bojongmekar';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ciharashas';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cipeundeuy';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ciroyom';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Jatimekar';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Margalaksana';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Margaluyu';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Nanggeleng';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Nyenang';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sirnagalih';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sirnaraja';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sukahaji';
			$data->id_kec = '7';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cigugur Girang';
			$data->id_kec = '8';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cihanjuang';
			$data->id_kec = '8';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cihanjuang Rahayu';
			$data->id_kec = '8';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cihideung';
			$data->id_kec = '8';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ciwaruga';
			$data->id_kec = '8';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Karyawangi';
			$data->id_kec = '8';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sariwangi';
			$data->id_kec = '8';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Batujajar Barat';
			$data->id_kec = '9';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Batujajar Timur';
			$data->id_kec = '9';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cangkorah';
			$data->id_kec = '9';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Galanggang';
			$data->id_kec = '9';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Giriasih';
			$data->id_kec = '9';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Pangauban';
			$data->id_kec = '9';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Bojonghaleuang';
			$data->id_kec = '10';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cikande';
			$data->id_kec = '10';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cipangeran';
			$data->id_kec = '10';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Girimukti';
			$data->id_kec = '10';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Jati';
			$data->id_kec = '10';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Saguling';
			$data->id_kec = '10';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cihampelas';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cipatik';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Citapen';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mekarjaya';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mekarmukti';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Pataruman';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Singajaya';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Situwangi';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Tanjungjaya';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Tanjungwangi';
			$data->id_kec = '11';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Batulayang';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Bongas';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Budiharja';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cililin';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Karanganyar';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Karangtanjung';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Karyamukti';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Kidangpananjung';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mukapayung';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Nanggerang';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Rancapanggung';
			$data->id_kec = '12';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Buninagara';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cicangkang Girang';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cikadu';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cintakarya';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mekarwangi';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Pasirpogor';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Puncaksari';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Ranca Senggang';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sindangkerta';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Wangunsari';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Weninggalih';
			$data->id_kec = '13';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Baranangsiang';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cibenda';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cicangkang Hilir';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cijambu';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cijenuk';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cintaasih';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Citalem';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Girimukti';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Karangsari';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Mekarsari';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Neglasari';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sarinagen';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sirnagalih';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sukamulya';
			$data->id_kec = '14';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Bunijaya';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Celak';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cilangari';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Gununghalu';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sindangjaya';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sirnajaya';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sukasari';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Tamanjaya';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Wargasaluyu';
			$data->id_kec = '15';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Bojong';
			$data->id_kec = '16';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Bojongsalam';
			$data->id_kec = '16';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cibedug';
			$data->id_kec = '16';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cibitung';
			$data->id_kec = '16';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cicadas';
			$data->id_kec = '16';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Cinengah';
			$data->id_kec = '16';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sukamanah';
			$data->id_kec = '16';
		$data->save();
        $data = new Kelurahan;
			$data->nama = 'Sukaresmi';
			$data->id_kec = '16';
		$data->save();
    }
}